let oneServing = [
  {
    id: "o0",
    url: "/share-apply/apply/o0",
    img: "/cook/public-assets/apply-content/ramen.jpg",
    img_alt: "ramen",
    kind: "1인분",
    title: "차슈라면 만들어주세요",
    content: "차슈라면이 너무 먹고싶어요.. 혹시 차슈라면 할 수 있는 분",
    location: "성수동",
    author: "미미",
    user_img: "/cook/public-assets/one-content/img1.png",
  },
  {
    id: "o1",
    url: "/share-apply/apply/o1",
    img: "/cook/public-assets/apply-content/stew.jpg",
    img_alt: "stew",
    kind: "1인분",
    title: "된장찌개!",
    content: "집밥이 너무 그리워서 된장찌개를 너무 먹고싶어요.",
    location: "행당동",
    author: "나라",
    user_img: "/cook/public-assets/one-content/img2.png",
  },
  {
    id: "o2",
    url: "/share-apply/apply/o2",
    img: "/cook/public-assets/apply-content/noodle.jpg",
    img_alt: "noodle",
    kind: "1인분",
    title: "잔치국수 먹고싶어요",
    content: "불어도 괜찮습니다! 전 다 잘 먹어요. 부탁드려요.",
    location: "성수동",
    author: "국수킬러",
    user_img: "/cook/public-assets/one-content/img3.png",
  },
  {
    id: "o3",
    url: "/share-apply/apply/o3",
    img: "/cook/public-assets/apply-content/grill.jpg",
    img_alt: "grill food",
    kind: "1인분",
    title: "닭꼬치 만들어주실 분!!!!",
    content: "맛있게만 만들어주세요!! 미리 잘 먹겠습니다",
    location: "사근동",
    author: "오늘은 내가",
    user_img: "/cook/public-assets/one-content/img4.png",
  },
  {
    id: "o4",
    url: "/share-apply/apply/o4",
    img: "/cook/public-assets/apply-content/burger.jpg",
    img_alt: "burger",
    kind: "1인분",
    title: "수제 햄버거가 너무 먹고싶어요",
    content: "밖에 나가도 수제 햄버거를 파는 집이 잘 안 보여서",
    location: "행당동",
    author: "오늘의집밥",
    user_img: "/cook/public-assets/one-content/img5.png",
  },
  {
    id: "oN",
    url: "/share-apply/apply/oN",
    img: "/cook/public-assets/apply-content/non-food-img.png",
    img_alt: "",
    kind: "1인분",
    title: "",
    content: "",
    location: "행당동",
    author: "",
    user_img: "/cook/public-assets/one-content/non-img.png",
  },
];

let dessert = [
  {
    id: "d0",
    url: "/share-apply/apply/d0",
    kind: "디저트",
    img: "/cook/public-assets/apply-content/macaron.jpg",
    img_alt: "macaron",
    title: "딸기 마카롱은 내가 최고다! 하는 분 들어오세요!!",
    content:
      "집에 오븐이 없어서 마카롱을 못 만들어요.. 혹시 마카롱 중에 딸기 마카롱 만들 수 있는 분 있을까요..? 가격은 부르는대로 낼게요!!!!",
    location: "사근동",
    author: "미미",
    user_img: "/cook/public-assets/one-content/img1.png",
  },
  {
    id: "d1",
    url: "/share-apply/apply/d1",
    kind: "디저트",
    img: "/cook/public-assets/apply-content/cupcake.jpg",
    img_alt: "cupcake",
    title: "친구 생일 선물로 컵케이크를 주고 싶어요.",
    content:
      "제가 만들고 싶은데 시간이 없어서 혹시 위 사진처럼 컵케이크 만들어주실 분 있을까요..? 부탁드립니다.",
    location: "사근동",
    author: "달콤한 세상",
    user_img: "/cook/public-assets/one-content/img2.png",
  },
  {
    id: "d2",
    url: "/share-apply/apply/d2",
    kind: "디저트",
    img: "/cook/public-assets/apply-content/chocolate-cake.jpg",
    img_alt: "chocolate cake",
    title: "초코 케이크 부탁드립니다.",
    content:
      "초코는 다크 초콜릿으로 만들어주셨으면 해요.크기는 8사람들이 다같이 먹을 수 있을 정도로 크게 만들어주세요.",
    location: "사근동",
    author: "초코",
    user_img: "/cook/public-assets/one-content/img3.png",
  },
  {
    id: "dN",
    url: "/share-apply/apply/dN",
    kind: "식기 및 도구",
    img: "/cook/public-assets/share-content/non-food-img.png",
    title: "",
    content: "",
    cost: "",
    location: "사근동",
    author: "",
    user_img: "/cook/public-assets/one-content/non-img.png",
  },
];

export { oneServing, dessert };
